/**
 * Maps ICAO airline designators (3 letters) to IATA codes (2 chars).
 * Client-side mirror of server/utils/icao-to-iata.ts.
 */
export const ICAO_TO_IATA: Record<string, string> = {
  AAL: "AA",
  ACA: "AC",
  AAR: "OZ",
  AFL: "SU",
  AFR: "AF",
  AIC: "AI",
  ANA: "NH",
  ANZ: "NZ",
  AAY: "G4",
  AMX: "AM",
  AWE: "US",
  AXM: "AK",
  AZA: "AZ",
  ITY: "AZ",
  AZU: "AD",
  BAW: "BA",
  BWA: "BW",
  BTI: "BT",
  CAL: "CI",
  CCA: "CA",
  CES: "MU",
  CSN: "CZ",
  CKK: "CK",
  CPA: "CX",
  CSZ: "C8",
  CLX: "CV",
  DAL: "DL",
  DLH: "LH",
  EIN: "EI",
  ELY: "LY",
  ETD: "EY",
  ETH: "ET",
  EVA: "BR",
  EZY: "U2",
  FDX: "FX",
  FFT: "F9",
  FIN: "AY",
  GIA: "GA",
  HAL: "HA",
  HVN: "VN",
  IBE: "IB",
  JAL: "JL",
  JBU: "B6",
  JST: "JQ",
  KAL: "KE",
  KLM: "KL",
  LAN: "LA",
  LOT: "LO",
  MAS: "MH",
  NAX: "DY",
  NCA: "KZ",
  OAL: "OA",
  PAL: "PR",
  QFA: "QF",
  QTR: "QR",
  RAM: "AT",
  RJA: "RJ",
  RYR: "FR",
  SAS: "SK",
  SIA: "SQ",
  SVA: "SV",
  SWA: "WN",
  SWR: "LX",
  TAM: "JJ",
  TAP: "TP",
  THA: "TG",
  THY: "TK",
  TGW: "TR",
  TVF: "TO",
  UAE: "EK",
  UAL: "UA",
  UPS: "5X",
  VIR: "VS",
  VLG: "VY",
  VOZ: "VA",
  WJA: "WS",
}

export function toIata(code: string): string {
  const normalized = code.trim().toUpperCase()
  if (normalized.length === 3 && normalized in ICAO_TO_IATA) {
    return ICAO_TO_IATA[normalized]!
  }
  return normalized
}
