/**
 * Maps IATA airport codes to ISO 3166-1 alpha-2 country codes.
 * Covers the ~200 busiest airports worldwide. If an airport is missing,
 * the visa badge simply won't show — no runtime error.
 */
export const iataToCountry: Record<string, string> = {
  // United States
  ATL: "US",
  LAX: "US",
  ORD: "US",
  DFW: "US",
  DEN: "US",
  JFK: "US",
  SFO: "US",
  SEA: "US",
  LAS: "US",
  MCO: "US",
  EWR: "US",
  MIA: "US",
  IAH: "US",
  BOS: "US",
  MSP: "US",
  DTW: "US",
  PHL: "US",
  CLT: "US",
  IAD: "US",
  SAN: "US",
  HNL: "US",
  // United Kingdom
  LHR: "GB",
  LGW: "GB",
  STN: "GB",
  MAN: "GB",
  EDI: "GB",
  // Japan
  NRT: "JP",
  HND: "JP",
  KIX: "JP",
  CTS: "JP",
  FUK: "JP",
  NGO: "JP",
  // China
  PEK: "CN",
  PVG: "CN",
  CAN: "CN",
  CTU: "CN",
  SZX: "CN",
  HKG: "HK",
  // South Korea
  ICN: "KR",
  GMP: "KR",
  PUS: "KR",
  // Singapore
  SIN: "SG",
  // Thailand
  BKK: "TH",
  DMK: "TH",
  CNX: "TH",
  HKT: "TH",
  // Malaysia
  KUL: "MY",
  PEN: "MY",
  BKI: "MY",
  KCH: "MY",
  LGK: "MY",
  SZB: "MY",
  // Indonesia
  CGK: "ID",
  DPS: "ID",
  SUB: "ID",
  // Vietnam
  SGN: "VN",
  HAN: "VN",
  DAD: "VN",
  // Philippines
  MNL: "PH",
  CEB: "PH",
  // India
  DEL: "IN",
  BOM: "IN",
  BLR: "IN",
  MAA: "IN",
  CCU: "IN",
  HYD: "IN",
  // Australia
  SYD: "AU",
  MEL: "AU",
  BNE: "AU",
  PER: "AU",
  // New Zealand
  AKL: "NZ",
  CHC: "NZ",
  WLG: "NZ",
  // UAE
  DXB: "AE",
  AUH: "AE",
  SHJ: "AE",
  // Turkey
  IST: "TR",
  SAW: "TR",
  AYT: "TR",
  // Germany
  FRA: "DE",
  MUC: "DE",
  BER: "DE",
  DUS: "DE",
  HAM: "DE",
  // France
  CDG: "FR",
  ORY: "FR",
  NCE: "FR",
  LYS: "FR",
  // Netherlands
  AMS: "NL",
  // Spain
  MAD: "ES",
  BCN: "ES",
  PMI: "ES",
  AGP: "ES",
  // Italy
  FCO: "IT",
  MXP: "IT",
  VCE: "IT",
  NAP: "IT",
  // Portugal
  LIS: "PT",
  OPO: "PT",
  // Switzerland
  ZRH: "CH",
  GVA: "CH",
  // Austria
  VIE: "AT",
  // Belgium
  BRU: "BE",
  // Ireland
  DUB: "IE",
  // Denmark
  CPH: "DK",
  // Sweden
  ARN: "SE",
  // Norway
  OSL: "NO",
  // Finland
  HEL: "FI",
  // Greece
  ATH: "GR",
  // Czech Republic
  PRG: "CZ",
  // Poland
  WAW: "PL",
  KRK: "PL",
  // Hungary
  BUD: "HU",
  // Canada
  YYZ: "CA",
  YVR: "CA",
  YUL: "CA",
  YYC: "CA",
  // Mexico
  MEX: "MX",
  CUN: "MX",
  GDL: "MX",
  // Brazil
  GRU: "BR",
  GIG: "BR",
  // Argentina
  EZE: "AR",
  // Chile
  SCL: "CL",
  // Colombia
  BOG: "CO",
  // Peru
  LIM: "PE",
  // South Africa
  JNB: "ZA",
  CPT: "ZA",
  // Egypt
  CAI: "EG",
  // Morocco
  CMN: "MA",
  // Kenya
  NBO: "KE",
  // Ethiopia
  ADD: "ET",
  // Qatar
  DOH: "QA",
  // Saudi Arabia
  RUH: "SA",
  JED: "SA",
  // Israel
  TLV: "IL",
  // Russia
  SVO: "RU",
  DME: "RU",
  LED: "RU",
  // Taiwan
  TPE: "TW",
  TSA: "TW",
  // Cambodia
  PNH: "KH",
  REP: "KH",
  // Myanmar
  RGN: "MM",
  // Sri Lanka
  CMB: "LK",
  // Maldives
  MLE: "MV",
  // Nepal
  KTM: "NP",
  // Bangladesh
  DAC: "BD",
  // Pakistan
  ISB: "PK",
  KHI: "PK",
  LHE: "PK",
  // Fiji
  NAN: "FJ",
  // Iceland
  KEF: "IS",
  // Croatia
  ZAG: "HR",
  DBV: "HR",
  SPU: "HR",
  // Romania
  OTP: "RO",
  // Bulgaria
  SOF: "BG",
  // Serbia
  BEG: "RS",
  // Laos
  VTE: "LA",
  LPQ: "LA",
}

/**
 * Resolve the country code for an IATA airport code.
 * Returns undefined if the airport is not in the map.
 */
export function getCountryForAirport(iataCode: string): string | undefined {
  return iataToCountry[iataCode.toUpperCase()]
}
